name: Bug Report
description: Found a bug in PLFile? Create a report!
title: "Insert title here"
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and the expected behavior
      placeholder: A clear and concise description of what the bug is, and what you expect to happen instead.
    validations:
      required: true
  - type: textarea
    id: error-log
    attributes:
      label: Error log
      description: The full error message
      placeholder: The full error message
    validations:
      required: true
  - type: input
    id: macos-version
    attributes:
      label: macOS version
      description: Which macOS version are you using?
      placeholder: "12.0"
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: Which package version are you using?
      placeholder: "0.1.0"
    validations:
      required: true
  - type: input
    id: xcode-version
    attributes:
      label: Xcode version
      description: Which version of Xcode are you using?
      placeholder: "14.3.0"
    validations:
      required: true
